#!/bin/sh

host="$(hostname)"
uptime="$(uptime -p | sed 's/up //')"
shell="$(basename "${SHELL}")"
terminal="$(basename "${TERMINAL}")"
os="$(cat /etc/system-release)"

if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# you can change these
c0="${reset}${black}"               # black
c1="${reset}${red}"                 # red
c2="${reset}${green}"               # green
c3="${reset}${yellow}"              # yellow
c4="${reset}${blue}"                # blue
c5="${reset}${magenta}"             # magenta
c6="${reset}${cyan}"                # cyan
c7="${reset}${white}"               # white
b0="${reset}${bold}${black}"        # bold black
b1="${reset}${bold}${red}"          # bold red
b2="${reset}${bold}${green}"        # bold green
b3="${reset}${bold}${yellow}"       # bold yellow
b4="${reset}${bold}${blue}"         # bold blue
b5="${reset}${bold}${magenta}"      # bold magenta
b6="${reset}${bold}${cyan}"         # bold cyan
b7="${reset}${bold}${white}"        # bold white

cat <<EOF
                
${b4}  /| ､       ${b4} ${USER}${c0}╶─╴${b4} ${host}${c0}╶─╴${c1} ${c2} ${c3} ${c4} ${c5} ${c6} ${c7} ${c0} 
${b2} (°､ ｡ 7     ${c0}┌${b2}  ${c0}╶─╴ ${c2}${os}
${b3}  |､  ~ヽ    ${c0}│${b3}  ${c0}╶─╴ ${c3}${uptime}
${b1}  じしf_,)〳 ${c0}└${b1}  ${c0}╶─╴ ${c1} ${shell} ${c0}─ ${c1} ${terminal}
${b1}                     
EOF
