#!/usr/bin/env bash

set -C -f
IFS="$(printf '%b_' '\n')"
IFS="${IFS%_}"

file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$(file -Lb --mime-type "$file")" =~ ^image ]]; then
	kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
	exit 1
fi

case "$(file --dereference --brief --mime-type -- "$1")" in
text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
text/troff) man ./ "$1" | col -b ;;
text/* | */xml | application/json) bat --terminal-width "$(($4 - 2))" -f "$1" ;;
audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
video/*)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
	[ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
	image "$CACHE" "$2" "$3" "$4" "$5" "$1"
	;;
*/pdf)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
	[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
	image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
	;;
*/epub+zip | */mobi*)
	CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
	[ ! -f "$CACHE.jpg" ] && gnome-epub-thumbnailer "$1" "$CACHE.jpg"
	image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
	;;
application/*zip) atool --list -- "$1" ;;
*opendocument*) odt2txt "$1" ;;
application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
